AWSTemplateFormatVersion: 2010-09-09
Description: A sample CloudFormation template with YAML comments.

# AWS cloudformation 
# - create stack
# - choose an existing template
# - upload a template file - next
# - enter stack name, next next submit

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: jenkins-server
      AvailabilityZone: us-east-1a
      ImageId: ami-084568db4383264d4 # Ubuntu Server 24.04 LTS (HVM),EBS General Purpose (SSD) Volume Type
      InstanceType: t2.medium # Due to build is done on server, T2 micro cannot handle the load 
      KeyName: jenkins-server
      SecurityGroupIds:
        - !Ref ServerSecurityGroup
        - sg-0c97817c6fc0f748b

  # our second EC2 security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Allow HTTP/HTTPS, SSH and Jenkins server port 8080 inbound and outbound traffic'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp:  0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp:  0.0.0.0/0